on: [push]

jobs:
  chain_bench_scan:
    runs-on: ubuntu-latest
    name: Rubyweeb app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install packages
        run: pip install boman-cli
      - name: Run scan  
        run: boman-cli -a run
