on: [push]

jobs:
  chain_bench_scan:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Chain Bench
        id: chain-bench
        uses: ./
        with:
          repository-url: https://github.com/Aj-tiara/cicd-goat-1.git
          github-token: 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

      - name: Echo
        run: echo ${{ steps.chain-bench.outputs.chain-bench-result }}
